### ISSUE TITLE
"Cannot use import statement outside a module" syntax error from inside puzzle-gen

### ISSUE THREAD

**Issue by trexrush** [tdecker91/puzzle-gen#4]
Trying to use this library in a svelte component, getting an error from inside the dist:

```
Cannot use import statement outside a module

/home/trexrush/dev/personal/cubing/node_modules/.pnpm/sr-puzzlegen@1.0.4/node_modules/sr-puzzlegen/dist/lib/index.js:1
import { TurnType } from "./algorithms/algorithm";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1027:15)
    at Module._compile (node:internal/modules/cjs/loader:1063:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:170:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
```
relevant code:
```svelte
import { CubeOptions, PNG, Type } from "sr-puzzlegen"
// ...
const newImage = (node: HTMLElement) => {
    let type: Type = Type.CUBE_TOP
    
    PNG(node, type, {})

    return {
        destroy(){}
      }
    }
//...
<div use:newImage /> 
```

same error occurs without a use directive too.
edit: code is irrelevent, the mere act of importing causes the issue

initial google search yields [this SO post](https://stackoverflow.com/questions/58384179/syntaxerror-cannot-use-import-statement-outside-a-module), which suggests: 
- define as module in the nearest parent `package.json`, which my app already was, but the nearest parent package.json is the one for puzzle-gen, and [this library does not use type: module](https://github.com/tdecker91/puzzle-gen/blob/master/package.json)

though since the package is a commonJS package, alternatively [publish as both cjs and esm?](https://stackoverflow.com/questions/61549406/how-to-include-commonjs-module-in-es6-module-node-app) or just explicitly define the package as a cjs module

do you have any ideas here? This is the only library with a megaminx visualization that fits my use case, I have until now been using your visualcube fork `sr-visualizer` which doesnt have this issue.

im not too familiar with dealing with dependencies in the js environment, so apologies if this isnt framed correctly.

**Comment by tdecker91** [comment]
Hey @trexrush 

Thanks for letting me know about the issue. I really appreciate your feedback. Sorry I'm not very familiar with JavaScript build and import systems, but I've been looking into it. It seems that the problem is related to the svelte app build configuration.

I came across this issue https://github.com/sveltejs/kit/issues/2161
suggesting that the libraries package.json should include `"type": "module"`, unfortunately this isn't as easy as just adding that in the package.json because there are other issues that pop up. As far as I understand, this is used for "Node.js" libraries. "sr-puzzlegen" as it is built cannot be run on Node.js (without using [custom renderers](https://tdecker91.github.io/puzzle-gen/#/advanced?id=custom-renderers))

The solution for Svelte is to add the following to your `vite.config.js` to tell svelte not to use the library in serverside rendering. (suggested as a work around in the issue thread)

```javascript
ssr: {
  noExternal: ['sr-puzzlegen']
}
```

This is necessary because the library uses the "window" object and is expected to run in the browser. `sr-visualizer` doesn't have this issue in svelte I think because the typescript is compiled to es6 instead of commonJs. 

I recreated the issue with a barebones svelte app, and was able to get it working by applying this suggestion. I hope it's suitable for your needs.

<img width="250" alt="Screen Shot 2023-07-25 at 10 06 05 AM" src="https://github.com/tdecker91/puzzle-gen/assets/3656030/e4ac62af-655a-46fa-9b7a-6bbfb27c7815">


It's possible there are better ways to bundle the library. One thing I can think of is split out the core logic from the code dependent on browsers. But this is not something I'm actively looking at.

 It's also possible that there are better ways I can configure the build that I'm not aware of. I'm also open to further suggestions and contributions if you have more expertise in configuring the module's build to ensure compatibility across the board.

Feel free to reach out if you have any additional insights or if there's anything else I can assist with.

edit: I looked more at bundling both cjs and esm modules. And on the surface this looks like something I'd like to do. Or at least have a way to tell the bundle that it doesn't expect to run in Node.js. I know the bundle config isn't spectacular. I'll have to play with it a bit. But either way I think if bundling a svelte app you'd still need to add the `noExternal` config.

**Comment by trexrush** [comment]
wow, thanks for the detailed response! 

My application is written with Astro as its metaframework, and uses SSG as opposed to SSR, so I was a little skeptical about the `noExternal` fix working, but it seems like it did! [Here is the commit where Im able to add puzzleGen](https://github.com/trexrush/algs/commit/a670a157a20a5bc2acde22b5f8d0dae975b28617) (the build failure is unrelated, ive fixed it)

I think long-term bundling both cjs and esm might help with issues like these, and needing `noExternal` in my use case, but for now the fix works so thank you!

Not sure if you want to keep the issue open for this or close it since my immediate issue has a workaround, up to you
